name: Style

on:
  pull_request:
    branches: ['main']

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo npm install -g markdownlint-cli
      - run: markdownlint .

  lint-source:
    name: Lint Source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
