name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.19', '1.20']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - run: go test ./...
