name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.19', '1.20']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - run: sudo apt-get install -qy squashfs-tools squashfs-tools-ng
      - run: go test ./...

  release-test:
    name: Release Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot --skip-publish
